name: Build documentation with JSCode
on:
  push:
    branches: [ master ]
    
jobs:
  build_doc:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Build doc
      uses: andstor/jsdoc-action@v1.1.0
      with:
        recurse: true
        output_dir: ./docs
        config_file: documentation.json
        template_name: jaguarjs-jsdoc
        front_page: README.md
        
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/\*.html
        git commit -m "rebuilt doc" -a
        git push origin master
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
